package com.buylk.backend.product;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@Configuration
public class ProductConfig {
    @Bean
    CommandLineRunner commandLineRunner(ProductRepository productRepository) {
        return args -> {
            productRepository.saveAll(
                    List.of(
                            new Product(null,
                                    "Cotton Collection Grey T-Shirt By Coco",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/181465949--1--1657860362.jpeg",
                                    2200.0,
                                    "gents",
                                    31),
                            new Product(null,
                                    "SACOOR BROTHERS Bordeaux Polo",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/R53M77R19BDX00L--1--1653376778.jpeg",
                                    26450.0,
                                    "gents",
                                    54),
                            new Product(null,
                                    "SACOOR BROTHERS Polo",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/183112910--1--1657860481.jpeg",
                                    22440.0,
                                    "gents",
                                    34),
                            new Product(null,
                                    "Fellini Regular Fit Solid Shirt",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/129709512--1--1582279438.jpeg",
                                    5650.0,
                                    "gents",
                                    65),

                            new Product(null,
                                    "Cotton Collection Printed Maxi Dress By Coco",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/CC0000007179--1--1595846528.jpeg",
                                    3960.0,
                                    "women",
                                    45),
                            new Product(null,
                                    "Cotton Collection Solid Color Halter Neck Mini Dress By Coco",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/146012080--1--1608613603.jpeg",
                                    3600.0,
                                    "women",
                                    35),
                            new Product(null,
                                    "Cotton Collection Cotton Mustard Tiered Dress By Coco",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/174114260--1--1640047488.jpeg",
                                    4220.0,
                                    "women",
                                    25),
                            new Product(null,
                                    "Cotton Collection Polyester Blend Black Printed Dress By Coco",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/174464286--1--1640048097.jpeg",
                                    3990.0,
                                    "women",
                                    24),
                            new Product(null,
                                    "Odel Basics Brick Red Short Sleeve Tshirt Dress",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/183665021--1--1654230697.jpeg",
                                    4550.0,
                                    "women",
                                    45),
                            new Product(null,
                                    "Cotton Collection Purple Dress By Coco",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/183863490--1--1657858481.jpeg",
                                    2650.0,
                                    "women",
                                    27),
                            new Product(null,
                                    "Boys printed casual shirt",
                                    "https://d1hj68zhrbkzii.cloudfront.net/wp-content/uploads/2022/05/0401801252BKP_KIDS_SHIRT_FASHIONBUG_SRI_LANKA-6.jpg",
                                    1300.0,
                                    "kids",
                                    35),
                            new Product(null,
                                    "Bug junior boys long sleeve shirt",
                                    "https://d1hj68zhrbkzii.cloudfront.net/wp-content/uploads/2022/05/0404000164WHT_KIDS_SHIRT_FASHIONBUG_SRI_LANKA-3.jpg",
                                    1200.0,
                                    "kids",
                                    65),
                            new Product(null,
                                    "Amy girls floral printed front bow tie cropped blouse",
                                    "https://d1hj68zhrbkzii.cloudfront.net/wp-content/uploads/2022/05/0507200126YLP-1_Girls_Blouse_Fashion-Bug-Sri-Lanka.jpg",
                                    1400.0,
                                    "kids",
                                    43),
                            new Product(null,
                                    "Amy girls floral printed front bow tie cropped blouse",
                                    "https://d1hj68zhrbkzii.cloudfront.net/wp-content/uploads/2022/05/0507200126LBP-1_Girls_Blouse_Fashion-Bug-Sri-Lanka.jpg",
                                    1320.0,
                                    "kids",
                                    22),
                            new Product(null,
                                    "Amy girls floral printed pin tuck blouse",
                                    "https://d1hj68zhrbkzii.cloudfront.net/wp-content/uploads/2022/05/0507300090BIP-2_Girls_Blouse_Fashion-Bug-Sri-Lanka.jpg",
                                    1505.0,
                                    "kids",
                                    12),
                            new Product(null,
                                    "Amy girls printed dress ",
                                    "https://d1hj68zhrbkzii.cloudfront.net/wp-content/uploads/2022/06/0504700907DBL-2_girls_Frock_Fashion_Bug_Sri_Lanka-100x100.jpg",
                                    1790.0,
                                    "kids",
                                    32),
                            new Product(null,
                                    "Fellini Men's Long Sleeve Slim Fit Printed Shirt",
                                    "https://objectstorage.ap-mumbai-1.oraclecloud.com/n/softlogicbicloud/b/cdn/o/products/400-600/152012650--1--1612869659.jpeg",
                                    6290.0,
                                    "gents",
                                    21)
                    )
            );
        };
    }
}
